### ISSUE TITLE
CONTEXT_LOST_WEBGL: loseContext: context lost

### ISSUE THREAD

**Issue by bernardogontijo** [twilio/twilio-video-processors.js#41]
In some old computers running Chrome 97.0.4692.99 on Windows 7, when the video call starts, the processors crash returning an error 
"CONTEXT_LOST_WEBGL: loseContext: context lost"

I think it is because of the load on the GPU. Any tips on how can I solve this?

**Comment by charliesantos** [comment]
Hi @bernardogontijo , thanks for submitting. This error usually happens if there's not enough hardware resources on the machine. In this case, it's most likely the GPU. Please try decreasing your capture resolution and see if that helps. If you're using a background image, please try using a smaller resolution image.

**Comment by bernardogontijo** [comment]
hi @charliesantos, thanks for the reply. Just adding more info, it started after an update of Chrome. The error is happing in Google Meet as well, so I can conclude that it is not related to this project.
